# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serializer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='serializer.proto',
  package='serializer',
  syntax='proto3',
  serialized_pb=_b('\n\x10serializer.proto\x12\nserializer\"\xb6\x01\n\nSerializer\x12\x11\n\tcharacter\x18\x01 \x01(\t\x12(\n\x08\x65xecutor\x18\x02 \x01(\x0b\x32\x14.serializer.ExecutorH\x00\x12*\n\tcommander\x18\x03 \x01(\x0b\x32\x15.serializer.CommanderH\x00\x12*\n\tcollector\x18\x04 \x01(\x0b\x32\x15.serializer.CollectorH\x00\x42\x13\n\x11\x63haracter_choices\")\n\x08\x45xecutor\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\";\n\tCommander\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0f\n\x07\x63lients\x18\x02 \x03(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x03(\t\"\x19\n\tCollector\x12\x0c\n\x04info\x18\x01 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SERIALIZER = _descriptor.Descriptor(
  name='Serializer',
  full_name='serializer.Serializer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='character', full_name='serializer.Serializer.character', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='executor', full_name='serializer.Serializer.executor', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commander', full_name='serializer.Serializer.commander', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='collector', full_name='serializer.Serializer.collector', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='character_choices', full_name='serializer.Serializer.character_choices',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=33,
  serialized_end=215,
)


_EXECUTOR = _descriptor.Descriptor(
  name='Executor',
  full_name='serializer.Executor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='serializer.Executor.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='args', full_name='serializer.Executor.args', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=258,
)


_COMMANDER = _descriptor.Descriptor(
  name='Commander',
  full_name='serializer.Commander',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='serializer.Commander.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clients', full_name='serializer.Commander.clients', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='args', full_name='serializer.Commander.args', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=319,
)


_COLLECTOR = _descriptor.Descriptor(
  name='Collector',
  full_name='serializer.Collector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='serializer.Collector.info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=346,
)

_SERIALIZER.fields_by_name['executor'].message_type = _EXECUTOR
_SERIALIZER.fields_by_name['commander'].message_type = _COMMANDER
_SERIALIZER.fields_by_name['collector'].message_type = _COLLECTOR
_SERIALIZER.oneofs_by_name['character_choices'].fields.append(
  _SERIALIZER.fields_by_name['executor'])
_SERIALIZER.fields_by_name['executor'].containing_oneof = _SERIALIZER.oneofs_by_name['character_choices']
_SERIALIZER.oneofs_by_name['character_choices'].fields.append(
  _SERIALIZER.fields_by_name['commander'])
_SERIALIZER.fields_by_name['commander'].containing_oneof = _SERIALIZER.oneofs_by_name['character_choices']
_SERIALIZER.oneofs_by_name['character_choices'].fields.append(
  _SERIALIZER.fields_by_name['collector'])
_SERIALIZER.fields_by_name['collector'].containing_oneof = _SERIALIZER.oneofs_by_name['character_choices']
DESCRIPTOR.message_types_by_name['Serializer'] = _SERIALIZER
DESCRIPTOR.message_types_by_name['Executor'] = _EXECUTOR
DESCRIPTOR.message_types_by_name['Commander'] = _COMMANDER
DESCRIPTOR.message_types_by_name['Collector'] = _COLLECTOR

Serializer = _reflection.GeneratedProtocolMessageType('Serializer', (_message.Message,), dict(
  DESCRIPTOR = _SERIALIZER,
  __module__ = 'serializer_pb2'
  # @@protoc_insertion_point(class_scope:serializer.Serializer)
  ))
_sym_db.RegisterMessage(Serializer)

Executor = _reflection.GeneratedProtocolMessageType('Executor', (_message.Message,), dict(
  DESCRIPTOR = _EXECUTOR,
  __module__ = 'serializer_pb2'
  # @@protoc_insertion_point(class_scope:serializer.Executor)
  ))
_sym_db.RegisterMessage(Executor)

Commander = _reflection.GeneratedProtocolMessageType('Commander', (_message.Message,), dict(
  DESCRIPTOR = _COMMANDER,
  __module__ = 'serializer_pb2'
  # @@protoc_insertion_point(class_scope:serializer.Commander)
  ))
_sym_db.RegisterMessage(Commander)

Collector = _reflection.GeneratedProtocolMessageType('Collector', (_message.Message,), dict(
  DESCRIPTOR = _COLLECTOR,
  __module__ = 'serializer_pb2'
  # @@protoc_insertion_point(class_scope:serializer.Collector)
  ))
_sym_db.RegisterMessage(Collector)


# @@protoc_insertion_point(module_scope)
